###
GET http://localhost:8080/clients/getClients

###
GET http://localhost:8080/clients/getClientDetails?clientName=Тарская ЦРБ

###
POST http://localhost:8080/clients/addClient
Content-Type: application/json

{
  "clientName": "Тарская ЦРБ",
  "clientAddress": "г. Тара, ул. Мира, 146"
}

###
PUT http://localhost:8080/clients/updateClient
Content-Type: application/json

{
  "clientName": "Тарская ЦРБ",
  "updatableData": {
    "clientNameNew": "БУЗОО Тарская ЦРБ",
    "clientAddressNew": "г. Тара, ул. Мира, 148"
  }
}

###
DELETE http://localhost:8080/clients/removeClient
Content-Type: application/json

{
  "clientName": "Тарская ЦРБ"
}
