###
GET http://localhost:8080/tenders/getTender?tenderNumber=125

###
POST http://localhost:8080/tenders/getTenders
Content-Type: application/json

{
  "clientName": "Тарская ЦРБ"
}

###
POST http://localhost:8080/tenders/addTender
Content-Type: application/json

{
  "clientName": "Тарская ЦРБ",
  "tenderNumber": "127",
  "tenderDate": "01.11.2020"
}

###
PUT http://localhost:8080/tenders/updateTender
Content-Type: application/json

{
  "clientName": "Тарская ЦРБ",
  "tenderNumber": "127",
  "updatableData": {
    "tenderNumberNew": "127",
    "tenderDateNew": "01.10.2020"
  }
}

###
DELETE http://localhost:8080/tenders/removeTender
Content-Type: application/json

{
  "clientName": "Тарская ЦРБ",
  "tenderNumber": "126"
}


