###
GET http://localhost:8080/tenderItems/getTenderItems?tenderNumber=125

###
POST http://localhost:8080/tenderItems/addTenderItem
Content-Type: application/json

{
  "tenderNumber": "125",
  "productName": "Диаскинтест1",
  "quantity": 5,
  "costPerUnit": 25.87
}

###
PUT http://localhost:8080/tenderItems/updateTenderItem
Content-Type: application/json

{
  "tenderNumber": "125",
  "productName": "Диаскинтест",
  "updatableData": {
    "productNameNew": "Диаскинтест",
    "quantityNew": 1,
    "costPerUnitNew": 50.75
  }
}

###
DELETE http://localhost:8080/tenderItems/removeTenderItem
Content-Type: application/json

{
  "tenderNumber": "125",
  "productName": "Диаскинтест1"
}


