###
GET http://localhost:8080/tenders/getAllTenders

###
GET http://localhost:8080/tenders/getClientTenders?clientName=Тарская ЦРБ

###
GET http://localhost:8080/tenders/getClientTender?clientName=Тарская ЦРБ&tenderNumber=125

###
POST http://localhost:8080/tenders/addClientTender
Content-Type: application/json

{
  "clientName": "Тарская ЦРБ",
  "tenderNumber": "127",
  "tenderDate": "01.11.2020"
}

###
PUT http://localhost:8080/tenders/updateClientTender
Content-Type: application/json

{
  "clientName": "Тарская ЦРБ",
  "tenderNumber": "127",
  "updatableData": {
    "tenderNumberNew": "127",
    "tenderDateNew": "01.10.2020"
  }
}

###
DELETE http://localhost:8080/tenders/removeClientTender
Content-Type: application/json

{
  "clientName": "Тарская ЦРБ",
  "tenderNumber": "127"
}


