###
GET http://localhost:8080/clients/getClients

###
POST http://localhost:8080/clients/addClient
Content-Type: application/json

{
  "clientName": "Тарская ЦРБ"
}

###
GET http://localhost:8080/products/getProducts

###
POST http://localhost:8080/products/addProduct
Content-Type: application/json

{
  "productName": "Диаскинтест1",
  "manufacturer": "ООО Биосинтез",
  "country": "Россия"
}

###
GET http://localhost:8080/tenders/getTenders?clientId=54d486b0-068c-4431-9026-2fe8dda2d29e
###
POST http://localhost:8080/tenders/addTender
Content-Type: application/json

{
  "clientId": "54d486b0-068c-4431-9026-2fe8dda2d29e",
  "tenderNumber": "124",
  "tenderDate": "01.10.2020",
  "tenderItems": [
    {
      "productId": "87652a05-ce8b-404b-ab20-f935702b54eb",
      "quantity": 5,
      "costPerUnit": 156.75
    },
    {
      "productId": "04163b3b-aac8-4802-be43-18c756ede375",
      "quantity": 10,
      "costPerUnit": 15.80
    }
  ]
}
