###
GET http://localhost:8080/clients/getClients

###
POST http://localhost:8080/clients/addClient
Content-Type: application/json

{
  "clientName": "Тарская ЦРБ"
}

###
GET http://localhost:8080/products/getProducts

###
POST http://localhost:8080/products/addProduct
Content-Type: application/json

{
  "productName": "Диаскинтест",
  "manufacturer": "ООО Биосинтез",
  "country": "Россия"
}

###
POST http://localhost:8080/tenders/getTenders
Content-Type: application/json

{
  "clientName": "Тарская ЦРБ"
}

###
GET http://localhost:8080/tenders/getTender?tenderNumber=125

###
POST http://localhost:8080/tenders/addTender
Content-Type: application/json

{
  "clientName": "Тарская ЦРБ",
  "tenderNumber": "127",
  "tenderDate": "01.11.2020"
}

###
PUT http://localhost:8080/tenders/updateTender
Content-Type: application/json

{
  "clientName": "Тарская ЦРБ",
  "tenderNumber": "127",
  "updatableData": {
    "tenderNumberNew": "127",
    "tenderDateNew": "01.10.2020"
  }
}

###
DELETE http://localhost:8080/tenders/deleteTender
Content-Type: application/json

{
  "clientName": "Тарская ЦРБ",
  "tenderNumber": "126"
}


