###
GET http://localhost:8080/clients/getClients

###
POST http://localhost:8080/clients/addClient
Content-Type: application/json

{
  "name": "Bob"
}

###
GET http://localhost:8080/products/getProducts

###
POST http://localhost:8080/products/addProduct
Content-Type: application/json

{
  "name": "Диаскинтест",
  "manufacturer": "ООО Биосинтез"
}
